### ISSUE TITLE
edit_headers is moving the email also to the Trash

### ISSUE THREAD

**Issue by milokmet** [johndoh/roundcube-markasjunk2#56]
Is possible to make edit_headers to only edit headers and move the message to Junk/Inbox instead of moving the copy of the original message to Trash?

**Comment by johndoh** [comment]
exactly what happens to the original message depends on how Roundcube is configured to do deletes but I suppose an option could be added to the driver to permanently remove it instead.

**Comment by johndoh** [comment]
one or two other drivers have similar functionality so I've added the new global optoin `markasjunk2_permanently_remove`. this should cover you case and any similar ones from other drivers.
