### ISSUE TITLE
"Not junk" not translated in french

### ISSUE THREAD

**Issue by ljoets** [johndoh/roundcube-markasjunk2#60]
Hi,
The string:
`$labels['notjunk'] = 'Not junk';`
is not translated in the fr_FR.inc file.
I suggest:
`$labels['notjunk'] = 'Acceptable';`

**Comment by johndoh** [comment]
Please submit a PR

**Comment by ljoets** [comment]
I didn't understand how do that :-(
"Create PR" button isn't active for me :-\
