### ISSUE TITLE
New Translation: zh_CN.inc

### ISSUE THREAD

**Issue by zhbzhbzhbz** [johndoh/roundcube-markasjunk2#61]
`<?php
/* Author: Denny Lin */

$labels = array();
$labels['buttonjunk'] = '标为垃圾邮件';
$labels['markasjunk'] = '标为垃圾邮件';
$labels['buttonnotjunk'] = '非垃圾邮件';
$labels['markasnotjunk'] = '非垃圾邮件';
$labels['notjunk'] = '非垃圾邮件';

$messages = array();
$messages['reportedasjunk'] = '已标为垃圾邮件';
$messages['reportedasnotjunk'] = '已移至收件箱';
`

**Comment by johndoh** [comment]
Please submit a PR
